spring:
  datasource:
    username: root
    password: fh789524560
    url: jdbc:mysql://localhost:3306/book?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**


mybatis:
  type-aliases-package: com.junxiaoniao.book.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
